name: Imprime data atual

on:
  push:
  
jobs:
  imprime_ubuntu-latest:
    name: Imprime data atual - Ubuntu-latest
    runs-on: ubuntu-latest
    
    steps:
      - name: Imprime data atual
        run: date
  

  imprime_windows-latest:
    name: Imprime data atual - Windows-latest
    runs-on: Windows-latest
    
    steps:
      - name: Imprime data atual
        run: date

  imprime_macos-latest:
    name: Imprime data atual - Macos
    runs-on: macos-latest
    
    steps:
      - name: Imprime data atual
        run: date
    
  imprime_imprimedatafinal:
    name: Imprime data final - dfinal
    runs-on: ubuntu-latest
    needs: [imprime_ubuntu-latest, imprime_windows-latest, imprime_macos-latest] 
    
    steps:
      - name: Imprime data atual
        run: date
