name: two workflow
on: push
 
jobs:
  checkout_code:
    name: status_workflow 
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v3.3.0
      - name: upload artefato
        uses: actions/upload-artifact@v3.1.2  
        with:
          name: ${{vars.artefato}}
          path: .
